# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-18 22:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20170118_2209'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articlelike',
            old_name='user',
            new_name='reader',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='user',
            new_name='reader',
        ),
        migrations.RenameField(
            model_name='commentlike',
            old_name='user',
            new_name='reader',
        ),
    ]
