# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-02-10 00:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20170125_0459'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='svg',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
