# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-23 03:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_auto_20170123_0316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='img',
            field=models.URLField(max_length=255),
        ),
    ]
