# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-08 00:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.CharField(max_length=32)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('img', models.CharField(max_length=255)),
                ('entry', models.TextField()),
            ],
        ),
    ]
