# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-08 00:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='slug',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
