# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-09 22:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_auto_20170108_0050'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='author',
            field=models.CharField(default='Mitchell Goff', max_length=255),
            preserve_default=False,
        ),
    ]
